// Generated by gtkmmproc -- DO NOT MODIFY!


#include <libmidgard2mm/libmidgard2.h>
#include <libmidgard2mm/private/libmidgard2_p.h>


namespace
{
} // anonymous namespace


class SomeType : public Glib::Object
{
  

protected:
  SomeType();

public:
  
  static Glib::RefPtr<SomeType> create(SECTION_SRC_CUSTOM p1);

/* Copyright (c) 2010  Joe Hacker <joe@example.com>
 *
 * This file is part of libmidgard2mm.
 *
 * libmidgard2mm is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 2.1 of the License,
 * or (at your option) any later version.
 *
 * libmidgard2mm is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Skeleton
{

} // namespace Skeleton


SomeType::SomeType()
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(0),
  Glib::Object(Glib::ConstructParams(sometype_class_.init()))
{
  

}

Glib::RefPtr<SomeType> SomeType::create(SECTION_SRC_CUSTOM p1)
{
  return Glib::RefPtr<SomeType>( new SomeType(p1) );
}
